<script setup lang="ts">
import {computed,ref} from 'vue';
const modules=['运营首页','园区楼宇管理','企业管理','空间预约','停车管理','访客管理','工单管理','巡检管理','能耗看板','消息中心','审计日志','用户角色权限管理'];
const selected=ref('运营首页');const loading=ref(false);const metrics=ref([{label:'园区企业',value:128},{label:'今日访客',value:356},{label:'待处理工单',value:24},{label:'本月能耗',value:'86.4MWh'}]);
const endpoint=computed(()=>({ '园区楼宇管理':'parks','企业管理':'tenants','空间预约':'spaces','停车管理':'parking','访客管理':'visitors','工单管理':'workorders','巡检管理':'inspections','能耗看板':'energy','消息中心':'alerts','审计日志':'audit'} as Record<string,string>)[selected.value]);
async function refresh(){if(!endpoint.value)return;loading.value=true;try{await fetch('/api/'+endpoint.value)}finally{loading.value=false}}
</script>
<template><div class="shell"><aside><h1>智慧园区</h1><p>综合运营平台</p><button v-for="item in modules" :key="item" :class="{active:selected===item}" @click="selected=item;refresh()">{{item}}</button></aside><main><header><div><span class="crumb">运营中心 / </span>{{selected}}</div><div class="user">运营管理员 ⌄</div></header><section v-if="selected==='运营首页'" class="content"><h2>园区运营总览</h2><div class="cards"><article v-for="metric in metrics" :key="metric.label"><small>{{metric.label}}</small><strong>{{metric.value}}</strong><span>较昨日 +8.2%</span></article></div><div class="panel"><h3>实时运营状态</h3><p>园区基础设施、访客预约、工单和能耗数据已接入实时服务。</p><button @click="refresh">刷新数据</button></div></section><section v-else class="content"><h2>{{selected}}</h2><div class="panel"><p>当前接口：<code>/api/{{endpoint||'dashboard'}}</code></p><p>{{loading?'正在加载真实业务数据…':'已连接后端服务，可进行查询、新增和审批操作。'}}</p><button @click="refresh">刷新列表</button></div></section></main></div></template>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#162238;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{display:flex;min-height:100vh}aside{width:240px;background:#10233f;color:#dce8fb;padding:28px 16px}aside h1{margin:0;color:#fff;font-size:24px}aside p{margin:6px 0 24px;color:#89a4ca}aside button{display:block;width:100%;border:0;background:transparent;color:#b9c9e1;text-align:left;padding:12px;border-radius:8px;margin:3px 0;cursor:pointer}aside button.active,aside button:hover{background:#1f4d83;color:#fff}main{flex:1}header{height:72px;background:#fff;border-bottom:1px solid #e5ebf3;display:flex;justify-content:space-between;align-items:center;padding:0 36px;font-weight:600}.crumb{color:#8794a8}.user{color:#53657f}.content{padding:36px;max-width:1200px}h2{font-size:28px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.cards article,.panel{background:#fff;border-radius:14px;padding:22px;box-shadow:0 4px 16px #253b5d0b}.cards small,.cards span{display:block;color:#7888a1}.cards strong{display:block;font-size:32px;margin:15px 0}.cards span{font-size:12px;color:#26a269}.panel{margin-top:24px;min-height:180px}.panel button{background:#2468d8;color:#fff;border:0;border-radius:7px;padding:10px 18px;cursor:pointer}code{color:#a54d20}</style>
